=== NALCORPallhat/jmetzen.github.com/publications/bib2html/bib2html.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:b2h="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  targetNamespace="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  attributeFormDefault="qualified"
  elementFormDefault="qualified">

<!-- First types that we may want to resuse -->
<xs:simpleType name="url_type">
 <xs:restriction base="xs:string" />
</xs:simpleType>

<!-- Now we define some element which will be used -->

<xs:element name="size">
 <xs:simpleType>
  <xs:restriction base="xs:nonNegativeInteger" />
 </xs:simpleType>
</xs:element>

<xs:element name="citation">
 <xs:simpleType>
  <xs:restriction base="xs:string" />
 </xs:simpleType>
</xs:element>

<xs:element name="file_format">
 <xs:simpleType>
  <xs:restriction base="xs:token">
    <xs:enumeration value="pdf" />
    <xs:enumeration value="ps" />
    <xs:enumeration value="ps.gz" />
    <xs:enumeration value="html" />
  </xs:restriction>
 </xs:simpleType>
</xs:element>

<xs:element name="index_link">
 <xs:complexType>
  <xs:all>
   <xs:element name="url" type="b2h:url_type"/>
   <xs:element name="name" type="xs:string"/>
  </xs:all>
 </xs:complexType>
</xs:element>

<xs:element name="main_index_links">
 <xs:complexType>
  <xs:sequence>
   <xs:element ref="b2h:index_link" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
 </xs:complexType>
</xs:element>

<xs:element name="download_entry">
 <xs:complexType>
  <xs:all>
   <xs:element ref="b2h:file_format" />
   <xs:element name="url" type="b2h:url_type" minOccurs="0" />
   <xs:element ref="b2h:size" minOccurs="0" />
   <xs:element name="exists" type="xs:boolean" />
  </xs:all>
 </xs:complexType>
</xs:element>

<xs:element name="download_links">
 <xs:complexType>
  <xs:sequence>
   <xs:element ref="b2h:download_entry" minOccurs="0" maxOccurs="unbounded"/>
  </xs:sequence>
 </xs:complexType>
</xs:element>

<xs:element name="generation_info">
 <xs:complexType>
  <xs:all>
   <xs:element name="program" type="xs:string" />
   <xs:element name="program_url" type="b2h:url_type" />
   <xs:element name="author" type="xs:string" />
   <xs:element name="author_url" type="b2h:url_type" />
   <xs:element name="datetime" type="xs:dateTime" />
  </xs:all>
 </xs:complexType>
</xs:element>

<xs:element name="group_papers">
 <xs:complexType>
  <xs:sequence>
   <xs:element name="group_title" type="xs:string" minOccurs="0"/>
   <xs:element ref="b2h:paper_info" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
 </xs:complexType>
</xs:element>

<xs:element name="list_group_papers">
 <xs:complexType>
  <xs:sequence>
   <xs:element ref="b2h:group_papers" minOccurs="1" maxOccurs="unbounded" />
  </xs:sequence>
 </xs:complexType>
</xs:element>

<xs:element name="paper_info">
 <xs:complexType>
  <xs:all>
   <xs:element name="title" type="xs:string"/>
   <xs:element ref="b2h:citation" />
   <xs:element ref="b2h:download_links" />
   <xs:element name="abstract" type="xs:string" minOccurs="0" />
   <xs:element name="bibtex_entry" type="xs:string" minOccurs="0" />
   <xs:element name="detail_url" type="b2h:url_type" minOccurs="0" />
  </xs:all>
 </xs:complexType>
</xs:element>

<!-- Now back to some type which we can reuse -->

<xs:complexType name="list_papers_type">
 <xs:all>
  <xs:element ref="b2h:main_index_links" />
  <xs:element name="list_title" type="xs:string"/>
  <xs:element ref="b2h:generation_info" />
  <xs:element ref="b2h:list_group_papers" />
 </xs:all>
</xs:complexType>


<!-- Now the main root element types -->

<xs:element name="paper_detail">
 <xs:complexType>
  <xs:all>
   <xs:element ref="b2h:main_index_links" />
   <xs:element ref="b2h:paper_info" />
   <xs:element ref="b2h:generation_info" />
  </xs:all>
 </xs:complexType>
</xs:element>

<xs:element name="main_index_page">
 <xs:complexType>
  <xs:all>
   <xs:element ref="b2h:main_index_links" />
   <xs:element ref="b2h:generation_info" />
  </xs:all>
 </xs:complexType>

</xs:element>

<!-- We use different names here to make it easy for a style sheet to do different
     things with the different types of pages -->

<xs:element name="list_papers_by_default" type="b2h:list_papers_type" />
<xs:element name="list_papers_by_date" type="b2h:list_papers_type" />
<xs:element name="list_papers_by_author" type="b2h:list_papers_type" />
<xs:element name="list_papers_by_pubtype" type="b2h:list_papers_type" />
<xs:element name="list_papers_by_rescat" type="b2h:list_papers_type" />
<xs:element name="list_papers_by_funding" type="b2h:list_papers_type" />

</xs:schema>

=== NALCORPallhat/jmetzen.github.com/publications/bib2html/listdate_ex.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<?xml-stylesheet type="text/xsl" href="trans_ex1.xsl"?>

<list_papers_by_date
  xmlns:b2h="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  xmlns="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html ./bib2html.xsd">

<main_index_links>
  <index_link>
   <name>Sorted by Date</name>
   <url>sort_date.html</url>
  </index_link>
  <index_link>
   <name>Classified by Publication Type</name>
   <url>class_type.html</url>
  </index_link>
  <index_link>
   <name>Classified by Research Category</name>
   <url>class_rescat.html</url>
  </index_link>
</main_index_links>


<list_title>
Sorted by Date
</list_title>



<generation_info>
 <program>bib2html</program>
 <program_url>http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html</program_url>
 <author>Patrick Riley</author>
 <author_url>http://www.cs.cmu.edu/~pfr</author_url>
 <datetime>2003-02-16T22:00:00-05:00</datetime>
</generation_info>

<list_group_papers>
 <group_papers>
  <group_title>2003</group_title>

  <paper_info>
   <title>Integration of Advice in an Action-Selection
   Architecture</title>
   <citation>Paul Carpenter, Patrick Riley, Manuela Veloso, and Gal
   Kaminka. Integration of Advice in an Action-Selection
   Architecture. In Gal A. Kaminka, Pedro U. Lima, and Raul Rojas,
   editors, RoboCup-2002: The Fifth RoboCup Competitions and
   Conferences, Springer Verlag, Berlin, 2003. (to appear)</citation>
   <download_links>
    <download_entry>
     <file_format>pdf</file_format>
     <url>./INTEG.pdf</url>
     <size> 12 </size>
     <exists>1</exists>
    </download_entry>
    <download_entry>
     <file_format>ps.gz</file_format>
     <url>./INTEG.ps.gz</url>
     <size> 68000 </size>
     <exists>true</exists>
    </download_entry>
   </download_links>
   <detail_url>testdetail.html</detail_url>
  </paper_info>

  <paper_info>
   <title>MPADES: Middleware for Parallel Agent Discrete Event Simulation</title>
   <citation>Patrick Riley. MPADES: Middleware for Parallel Agent Discrete Event Simulation. In Gal A. Kaminka, Pedro U. Lima, and Raul Rojas, editors, RoboCup-2002: The Fifth RoboCup Competitions and Conferences, Springer Verlag, Berlin, 2003. (to appear)</citation>
   <download_links>
    <download_entry>
     <file_format>pdf</file_format>
     <url>./MPADES.pdf</url>
     <size> 12 </size>
     <exists>0</exists>
    </download_entry>
    <download_entry>
     <file_format>ps.gz</file_format>
     <url>./MPADES.ps.gz</url>
     <size> 68000 </size>
     <exists>true</exists>
    </download_entry>
   </download_links>
   <!-- <detail_url>testdetail.html</detail_url> -->
  </paper_info>

 </group_papers>

 <group_papers>
  <group_title>2002</group_title>

  <paper_info>
   <title>ChaMeleons-01 Team Description</title>
   <citation>Paul Carpenter, Patrick Riley, Gal Kaminka, Manuela Veloso, Ignacio Thayer, and Robert Wang. ChaMeleons-01 Team Description. In Andreas Birk, Silvia Coradeschi, and Satoshi Tadokoro, editors, RoboCup-2001: Robot Soccer World Cup V, Springer, Berlin, 2002.</citation>
   <download_links>
    <download_entry>
     <file_format>pdf</file_format>
     <url>./TD.pdf</url>
     <size> 12 </size>
     <exists>1</exists>
    </download_entry>
    <download_entry>
     <file_format>ps.gz</file_format>
     <url>./TD.ps.gz</url>
     <size> 68000 </size>
     <exists>false</exists>
    </download_entry>
   </download_links>
   <detail_url>AIPS02-STN.html</detail_url>
  </paper_info>
  
 </group_papers>

</list_group_papers>

</list_papers_by_date>

=== NALCORPallhat/jmetzen.github.com/publications/bib2html/detail_ex.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<?xml-stylesheet type="text/xsl" href="trans_ex1.xsl"?>

<paper_detail 
  xmlns:b2h="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  xmlns="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html ./bib2html.xsd">

<main_index_links>
  <index_link>
   <name>Sorted by Date</name>
   <url>sort_date.html</url>
  </index_link>
  <index_link>
   <name>Classified by Publication Type</name>
   <url>class_type.html</url>
  </index_link>
  <index_link>
   <name>Classified by Research Category</name>
   <url>class_rescat.html</url>
  </index_link>
</main_index_links>

<paper_info>

<title>
MPADES: Middleware for Parallel Agent Discrete Event
Simulation
</title>

<citation>
<![CDATA[
Patrick Riley. MPADES: Middleware for Parallel Agent Discrete Event
Simulation. In Gal A. Kaminka, Pedro U. Lima, and Raul Rojas, editors,
<i>RoboCup-2002: The Fifth RoboCup Competitions                  and
Conferences</i>, Springer Verlag, Berlin, 2003. (to appear)<br /> Won a
<b>RoboCup Engineering Award</b>  
]]>
</citation>

<download_links>
  <download_entry>
   <file_format>pdf</file_format>
   <url>./LNAI02-mpades.pdf</url>
   <size> 0 </size>
   <exists>0</exists>
  </download_entry>
  <download_entry>
   <file_format>ps.gz</file_format>
   <url>./LNAI02-mpades.ps.gz</url>
   <size> 68000 </size>
   <exists>true</exists>
  </download_entry>
</download_links>

<abstract>
<![CDATA[
Simulations are an excellent tool for studying
artificial intelligence. However, the simulation
technology in use by and designed for the artificial
intelligence community often fails to take advantage
of much of the work by the larger simulation
community to produce stable, repeatable, and
efficient simulations. We present the new system
Middleware for Parallel Agent Discrete Event
Simulation (MPADES) as a simulation substrate for                  the
artificial intelligence community. MPADES                  focuses on
the agent as a fundamental simulation                  component. The
``thinking time'' of an agent is                  tracked and
reflected in the results of the agents'
actions. MPADES supports and manages the                  distribution
of agents across machines while being                  robust to
variations in network performance and                  machine
load. We present the system in detail and                  give
experimental results for a simple world model                  and set
of agents. MPADES is not tied to any                  particular
simulation, and is a powerful new tool                  for creating
simulations for the study of artificial
intelligence. 
]]>
</abstract>

<bibtex_entry>
<![CDATA[
@InCollection(LNAI02-mpades,
  Author =	 "Patrick Riley",
  Title =	 "{MPADES}: Middleware for Parallel Agent Discrete Event
                  Simulation",
  booktitle =	 "{R}obo{C}up-2002: The Fifth {R}obo{C}up Competitions
                  and Conferences",
  Editor =	 "Gal A. Kaminka and Pedro U. Lima and Raul Rojas",
  Publisher =	 "Springer Verlag",
  address =	 "Berlin",
  year =	 2003,
  wwwnote =	 {Won a <b>RoboCup Engineering Award</b>},
  note =	 {(to appear)},
  abstract =	 {Simulations are an excellent tool for studying
                  artificial intelligence. However, the simulation
                  technology in use by and designed for the artificial
                  intelligence community often fails to take advantage
                  of much of the work by the larger simulation
                  community to produce stable, repeatable, and
                  efficient simulations. We present the new system
                  Middleware for Parallel Agent Discrete Event
                  Simulation (MPADES) as a simulation substrate for
                  the artificial intelligence community. MPADES
                  focuses on the agent as a fundamental simulation
                  component. The ``thinking time'' of an agent is
                  tracked and reflected in the results of the agents'
                  actions. MPADES supports and manages the
                  distribution of agents across machines while being
                  robust to variations in network performance and
                  machine load. We present the system in detail and
                  give experimental results for a simple world model
                  and set of agents. MPADES is not tied to any
                  particular simulation, and is a powerful new tool
                  for creating simulations for the study of artificial
                  intelligence. },
  bib2html_pubtype = {Refereed Conference,Award Winner},
  bib2html_rescat = {Simulation},
)
]]>
</bibtex_entry>

</paper_info>

<generation_info>
 <program>bib2html</program>
 <program_url>http://www.cs.cmu.edu/~pfr/misc_software/index.html#bib2html</program_url>
 <author>Patrick Riley</author>
 <author_url>http://www.cs.cmu.edu/~pfr</author_url>
 <datetime>2003-02-16T22:00:00-05:00</datetime>
</generation_info>

</paper_detail>
